[preferred]
default=kde;
org.freedesktop.impl.portal.Access=kde;
org.freedesktop.impl.portal.Notification=kde;
org.freedesktop.impl.portal.Secret=gnome-keyring;
org.freedesktop.impl.portal.FileChooser=kde;
